---
kind: pipeline
type: docker
name: terraform-provider-couchbase

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: linter
    image: golang
    commands:
      - apt-get update && apt-get install -yy python3 python3-pip shellcheck build-essential
      - pip3 install yamllint
      - go install golang.org/x/lint/golint
      - make linters

  - name: run tests
    image: golang
    commands:
      - make cbinit
      - make test
      - make testacc
    environment:
      CB_ADDRESS: couchbase
      CB_CLIENT_PORT: 8091
      CB_NODE_PORT: 11210
      CB_PASSWORD: 123456
      CB_USERNAME: Administrator

  - name: notify slack
    image: golang
    settings:
      channel:
        from_secret: slack_channel
      link_names: true
      username:
        from_secret: slack_username
      template: |
        {{#success build.status}}
          *✅ Succeeded - project {{repo.name}}:*
          - build {{build.number}}
          - commit {{build.commit}}
          - branch {{build.branch}}
          - event {{build.event}}
          - PR {{build.pull}}
          - link {{build.link}}
        {{else}}
          *❌ Failed - project {{repo.name}}:*
          - build {{build.number}}
          - commit {{build.commit}}
          - branch {{build.branch}}
          - event {{build.event}}
          - PR {{build.pull}}
          - link {{build.link}}
        {{/success}}
      webhook:
        from_secret: slack_webhook
    when:
      status:
        - success
        - failure

  - name: release
    image: goreleaser/goreleaser
    commands:
      - goreleaser release
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      event:
        - tag

services:
  - name: couchbase
    image: couchbase

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
    - tag

---
kind: signature
hmac: 788240a36eb57d0dc27bbec122aa45c9b2eedf5a9639769134c546c4255f1489

...
