---
kind: pipeline
type: docker
name: terraform-provider-couchbase

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: linter
    image: golang
    commands:
      - apt-get update && apt-get install -yy python3 python3-pip shellcheck build-essential
      - pip3 install yamllint
      - go install golang.org/x/lint/golint
      - make linters

  - name: run tests
    image: golang
    commands:
      - make cbinit
      - make test
      - make testacc
    environment:
      CB_ADDRESS: couchbase
      CB_CLIENT_PORT: 8091
      CB_NODE_PORT: 11210
      CB_PASSWORD: 123456
      CB_USERNAME: Administrator

  - name: release
    image: goreleaser/goreleaser
    commands:
      - goreleaser release
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      event:
        - tag

services:
  - name: couchbase
    image: couchbase

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
    - tag

---
kind: signature
hmac: a604c1918bf81e413e1c528bab1a3319bddbaad567f10775738ffc5b08d1bd9a

...
